Create a playbook called copy.yml under /home/bob/playbooks/ directory to copy /usr/src/blog/index.html file to both nodes i.e node01 and node02 at location /opt/blog

SOL:
Run below command:


vi /home/bob/playbooks/copy.yml



Add below code in it and save:


---
- hosts: all
  become: true
  tasks:
    - copy:
        src:  /usr/src/blog/index.html
        dest: /opt/blog
        remote_src: yes



Run the playbook using below command:


cd /home/bob/playbooks
ansible-playbook -i inventory copy.yml
