The playbook /home/bob/playbooks/banana.yml has a variable defined called fruit. There are two tasks written in this playbook to print a text.



Use the when conditional to print I am a Banana if the value of fruit is banana otherwise it should print I am not a Banana.

SOL:
Edit the playbook:


vi /home/bob/playbooks/banana.yml



Modify the /home/bob/playbooks/banana.yml playbook as below:


---
- name: 'Am I a Banana or not?'
  hosts: localhost
  connection: local
  vars:
    fruit: banana
  tasks:
    - command: 'echo "I am a Banana"'
      when: fruit == "banana"

    - command: 'echo "I am not a Banana"'
      when: fruit != "banana"



Run the playbook in verbose as below:


cd /home/bob/playbooks
ansible-playbook -i localhost, banana.yml -vv
